### ISSUE TITLE
UPDATE??

### ISSUE THREAD

**Issue by jmsandamil** [Samaritan1011001/Trovami#13]
Will you update this project? 

thank you¡¡¡

**Comment by Samaritan1011001** [comment]
I have updated the project to work with androidx with the latest commit. However, I do not have a Mac to run it and check on IOS.

**Comment by jmsandamil** [comment]
I will try it in iOS and tell you

**Comment by jmsandamil** [comment]
don't work 

in android get error,

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building Container(constraints: BoxConstraints(w=392.7, h=759.3)):
The getter 'value' was called on null.
Receiver: null
Tried calling: value

The relevant error-causing widget was: 
  Container file:/// /Trovami-master/lib/homepage.dart:60:13
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      homepagestate.getgroups (package:trovami/homepage.dart:145:15)
#2      homepagestate.initState (package:trovami/homepage.dart:159:25)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4428:58)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4274:5)
...

**Comment by Samaritan1011001** [comment]
@jmsandamil  Can you tell me which phone did you try it on? 
I tried it on a Pixel 2XL and it works just fine.

**Comment by jmsandamil** [comment]
Android studio emulador, 3a

**Comment by Samaritan1011001** [comment]
Yeah. I tried that and it seems to work fine. Can you give me more details? When exactly you get the error and your flutter version.

**Comment by josephpaulmckenzie** [comment]
I can confirm I also receive the same error as jmsandamil . I am using an Galaxy S10 . I am able to create an account and once I try to login using that account I get the above error.  I also encountered a few other things you may wish to know about if you were not aware . I'll send you a direct email as I have your email ;)

**Comment by PierrieK** [comment]
Also receive the same error on Huawei P30 Pro Android build 10.0.0.178.

**Comment by Samaritan1011001** [comment]
@jmsandamil The latest commit should fix the error. If not, let me know. 

@josephpaulmckenzie I appreciate your concern and I have now taken out the google sign in button and also added a warning text above the email field on the sign up screen. This should be fine for now. I'll plan to anonymize the emails when I get more time to work on this.
